<a href="https://colab.research.google.com/github/007-athul/DSA-case-study1/blob/main/numpy_pandas_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
#task1
import pandas as pd
import numpy as np

In [103]:
#task 2
data=pd.read_csv('IMDB-Movie-Data.csv')

In [104]:
#task 3
#shape
data.shape

(1000, 12)

In [105]:
#head
data.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [106]:
#column names
data.columns.tolist()

['Rank',
 'Title',
 'Genre',
 'Description',
 'Director',
 'Actors',
 'Year',
 'Runtime (Minutes)',
 'Rating',
 'Votes',
 'Revenue (Millions)',
 'Metascore']

In [107]:
#datatype
data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [108]:
#missing values
data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [109]:
#task 4
#checking for duplicated
data.duplicated().sum()

np.int64(0)

In [110]:
#removing duplocated values
data=data.drop_duplicates()

In [111]:
#task 5
#renaming column name
data=data.rename(columns={'Title':'Movie_Title'})
data.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [112]:
#task 6
# to get unique genre names
data['Genre'].unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [113]:
#task 7
#genre count per movie
data['Genre_Count']= data['Genre'].str.split(",").str.len()
data[['Movie_Title','Genre','Genre_Count']].head()

               Movie_Title                     Genre  Genre_Count
0  Guardians of the Galaxy   Action,Adventure,Sci-Fi            3
1               Prometheus  Adventure,Mystery,Sci-Fi            3
2                    Split           Horror,Thriller            2
3                     Sing   Animation,Comedy,Family            3
4            Suicide Squad  Action,Adventure,Fantasy            3

In [114]:
#task 8
#Handle missing values in 'Revenue (Millions)' and 'Metascore
data['Revenue (Millions)']=data['Revenue (Millions)'].fillna(
    data['Revenue (Millions)'].mean())

data['Metascore']= data['Metascore'].fillna(
    data['Metascore'].mean())

data[['Revenue (Millions)', 'Metascore']].isnull().sum()

Revenue (Millions)    0
Metascore             0
dtype: int64

In [115]:
#task9
#Top 5 movies by Rating
top5= data.sort_values(by='Rating',ascending=False)
top5[['Movie_Title','Rating']].head()

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [116]:
#task 10
#Movies with highest/lowest revenue

highest_revenue=data['Revenue (Millions)'].idxmax()
lowest_revenue=data['Revenue (Millions)'].idxmin()
print(f"Highest Revenue :{data.loc[highest_revenue,'Movie_Title']}\n Lowest Revenue :{data.loc[lowest_revenue,'Movie_Title']}")

Highest Revenue :Star Wars: Episode VII - The Force Awakens
 Lowest Revenue :A Kind of Murder

In [117]:
#task11
#Avg. rating by Director
data.groupby('Director')['Rating'].mean()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

In [118]:
#task12
#Movies per year
data['Year'].value_counts()

Year
2016    297
2015    127
2014     98
2013     91
2012     64
2011     63
2010     60
2007     53
2008     52
2009     51
2006     44
Name: count, dtype: int64

In [119]:
#task 13
#Movies with rating > 8 & revenue > 100M
data.loc[(data['Rating'] > 8) & (data['Revenue (Millions)'] > 100),'Movie_Title']

0                           Guardians of the Galaxy
6                                        La La Land
36                                     Interstellar
50       Star Wars: Episode VII - The Force Awakens
54                                  The Dark Knight
67                               Mad Max: Fury Road
74                                         Zootopia
76                                     The Avengers
77                             Inglourious Basterds
80                                        Inception
82                          The Wolf of Wall Street
83                                        Gone Girl
92                                         The Help
99                                     The Departed
114    Harry Potter and the Deathly Hallows: Part 2
124                           The Dark Knight Rises
138                                  Shutter Island
144                                Django Unchained
241                                      Inside Out
427                            The Bourne Ultimatum
499                                              Up
634                                          WALL·E
645                                     Gran Torino
688                                     Toy Story 3
772                        How to Train Your Dragon
Name: Movie_Title, dtype: object

In [120]:
#task14
#Group by Director: avg Rating, Revenue
data.groupby('Director')[['Rating','Revenue (Millions)']].mean()

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

In [121]:
#task 15
#Group by Year: count, avg Rating
data.groupby('Year')['Rating'].agg(['count', 'mean'])

      count      mean
Year
2006     44  7.125000
2007     53  7.133962
2008     52  6.784615
2009     51  6.960784
2010     60  6.826667
2011     63  6.838095
2012     64  6.925000
2013     91  6.812088
2014     98  6.837755
2015    127  6.602362
2016    297  6.436700

In [122]:
#task16
#Create a new column Profitability:
#a) Revenue divided by Duration
data['Profitability'] = data['Revenue (Millions)'] / data['Runtime (Minutes)']
data.head()

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Genre_Count,Profitability
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3,2.753140
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3,1.019839
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2,1.180513
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3,2.502963
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3,2.642439

In [123]:
#b) Find top 10 most profitable movies
top10 = data.sort_values('Profitability', ascending=False)

print(top10[['Movie_Title', 'Profitability']].head(10))

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [124]:
#task17
#17) Create a column that categorizes movies by rating:
#a) Rating < 6: Poor
#b) 6 ≤ Rating < 7.5: Average
#c) Rating ≥ 7.5: Excellent
data['Rating_Category'] = data['Rating'].apply(
    lambda x: 'Poor' if x < 6
    else 'Average' if x < 7.5
    else 'Excellent'
)
print(data[['Movie_Title', 'Rating', 'Rating_Category']].head())

               Movie_Title  Rating Rating_Category
0  Guardians of the Galaxy     8.1       Excellent
1               Prometheus     7.0         Average
2                    Split     7.3         Average
3                     Sing     7.2         Average
4            Suicide Squad     6.2         Average

In [125]:
#task18
#Create a custom function to score movies based on:
#i) Apply row['Rating'] * 10 + row['Revenue (Millions)'] as High score
#Apply a function to dataset to assign the score

def movie_score(row):
    return row['Rating'] * 10 + row['Revenue (Millions)']

data['Score'] = data.apply(movie_score, axis=1)

print(data[['Movie_Title', 'Score']].head())

               Movie_Title   Score
0  Guardians of the Galaxy  414.13
1               Prometheus  196.46
2                    Split  211.12
3                     Sing  342.32
4            Suicide Squad  387.02